server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: emp
          uri: http://localhost:8082/
          predicates:
            - Path=/employee/**
        - id: con
          uri: http://localhost:8081/
          predicates:
            - Path=/consumer/**